WIP updating the analyses
synthetichealth/rif-analysis pull request #1
Opened 2023-04-04 19:49 UTC by lkasaitis

2023-04-14 20:16 UTC, jawalonoski requested changes
There are a couple of errors that need to be corrected, especially references to `beneficiary_final.csv` which does not exist after conversion from BFD to CCW format.

2023-04-14 20:16 UTC, jawalonoski commented on beneficiary_final_demographics.ipynb
Does not work because `beneficiary_final.csv` does not exist. Should it be `data/beneficiary_2022.csv`?

2023-04-14 20:16 UTC, jawalonoski commented on beneficiary_final_demographics.ipynb
When attempts to use `beneficiary_2022.csv`:

```
ValueError: Usecols do not match columns, columns expected but not found: ['BENE_SEX_IDENT_CD', 'AGE']
```

2023-04-14 20:16 UTC, jawalonoski commented on chronic_conditions_apriori.ipynb
Again `beneficiary_final.csv` is not one of the files.

2023-04-14 20:16 UTC, jawalonoski commented on synthetic_readmissions_sdoh.ipynb
Replacing `beneficiary_final.csv` with `beneficiary_2022.csv` does not work -- column name error:

```
ValueError: Usecols do not match columns, columns expected but not found: ['BENE_SEX_IDENT_CD', 'FIPS_STATE_CNTY_JAN_CD', 'AGE']
```

2023-04-14 20:16 UTC, jawalonoski commented on synthetic_readmissions_sdoh_+_race.ipynb
Replacing beneficiary_final.csv with beneficiary_2022.csv does not work -- column name error:

```
ValueError: Usecols do not match columns, columns expected but not found: ['BENE_SEX_IDENT_CD', 'FIPS_STATE_CNTY_JAN_CD', 'AGE']
```

2023-04-14 20:16 UTC, jawalonoski commented on unique_claims_per_beneficiary.ipynb
Error on reading `pde.csv`
```
ValueError: Usecols do not match columns, columns expected but not found: ['CLM_GRP_ID']
```

2023-04-17 21:42 UTC, jawalonoski commented on synthetic_feature_selection_input.ipynb
Running this notebook yields:
```
ValueError: Usecols do not match columns, columns expected but not found: ['BENE_ENTLMT_RSN_CURR']
```

The correct column should be `ENTLMT_RSN_CURR`.

2023-04-17 21:44 UTC, jawalonoski commented on synthetic_sdoh_feature_selection_limit_feature_class.ipynb
I was unable to run this notebook successfully, as `synthetic_feature_selection_input.ipynb` did not complete successfully.

2023-04-17 21:45 UTC, jawalonoski requested changes
Some of my previous comments seem to be related to my repo being out of date.

I encountered an additional two issues...

2023-04-18 14:53 UTC, lkasaitis commented on synthetic_feature_selection_input.ipynb
Corrected column to ```ENTLMT_RSN_CURR```.

2023-04-18 14:54 UTC, lkasaitis commented on synthetic_sdoh_feature_selection_limit_feature_class.ipynb
reran after correcting ```synthetic_feature_selection_input.ipynb```

2023-04-20 14:32 UTC, jawalonoski commented on synthetic_feature_selection_input.ipynb
On saving the data frame as Excel, I now get

```
ModuleNotFoundError: No module named 'xlsxwriter'
```

Either the notebook is missing an `import`, or we need to update the `requirements.txt` file, or both.

2023-04-20 20:15 UTC, lkasaitis commented on synthetic_feature_selection_input.ipynb
added ```import xlsxwriter``` to ```synthetic_feature_selection_input.ipynb``` and updated the ```requirements.txt``` file.

2023-04-20 21:08 UTC, jawalonoski approved these changes

2023-04-20 21:08 UTC, merged